spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_db

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop